### ISSUE TITLE
Don't include data use conditions in this version

### ISSUE THREAD

**Issue by mfiume** [ga4gh/beacon-team#15]
Proposal by Jordi.

**Comment by mcupak** [comment]
For reference, this contradicts #22. Since data use conditions are ready, I vote for rejecting this issue.

**Comment by antbro** [comment]
I think we did not fully agree how best to represent different data use condition frameworks, and so rather than toss a coin at this stage we'd do better to reach a consensus and include that in the next version. Several voices have advised against inclusion now.

Cheers

Tony





________________________________

**Comment by sdelatorrep** [comment]
+1 to not including them in this version

**Comment by mfiume** [comment]
Ok, as per our TC, moving this to 0.4 with the understanding that we should start to discuss data use conditions with Beacon operators.

**Comment by mcupak** [comment]
Addition of consent codes was pushed to 0.4, removal was agreed for 0.3. Reverting the milestone.

**Comment by mbaudis** [comment]
+1
