### ISSUE TITLE
Drop global “exists” and “includeDatasetDetails” fields 

### ISSUE THREAD

**Issue by mfiume** [ga4gh/beacon-team#17]
Proposal by @mcupak, please elaborate.

**Comment by mcupak** [comment]
It seems this would clean up some mess - we wouldn’t need to specify any magical behaviour then (e.g. return all if not specified, which could be a problem for big beacons). There would also be no need for the includeDatasetDetails parameter (which only affects what kind of data to display anyway), and there would be no need for a global beacon exists response (which is basically redundant already).

We’ve already made it compulsory for the beacon to describe its datasets as part of its info, so it seems we’re almost there. It might be a matter of perspective - getting used to querying datasets instead of querying beacons.

A request would then look like this (always - all parameters mandatory):
```
GET /query?referenceName=1&start=1000&referenceBases=A&alternateBases=C&assemblyId=GRCh37&datasetIds=d1
```

The response would have the following form (requested datasets included):
```javascript
{
  "beaconId":"foo",
  "datasetAlleleResponses":[
    {
      "datasetId":"d1",
      "exists":true
    }
  ]
}
```

**Comment by mfiume** [comment]
Another consideration along this train of thought is to embed the dataset ID in the URL

```
GET /dataset/{datasetId}/query?referenceName=1&start=1000&referenceBases=A&alternateBases=C&assemblyId=GRCh37
```

This precludes one from querying across multiple datasets in a beacon using a single request, but perhaps simplifies our logic substantially.

Just an option to consider.

**Comment by mcupak** [comment]
I think the ability to query multiple (all) the datasets in a single request is very important, for example for the Beacon Network. I would only compromise on the format and the defaults, but definitely not sacrifice this feature completely.

**Comment by jrambla** [comment]
-1
Again, allowing for flexibility in the request should allow the caller to choose the option that better fits his needs: short vs detailed, summary vs. by dataset...

**Comment by mcupak** [comment]
For reference, this issue contradicts #10 and #11.

**Comment by mcupak** [comment]
Rejected.
