### ISSUE TITLE
Should we always show all the datasets in BeaconDatasetAlleleResponse?

### ISSUE THREAD

**Issue by sduvaud** [ga4gh/beacon-team#56]
Is it ok for the user to get back the whole bunch of dataset allele responses if only 1 or 2 has a match?
One the one hand, the fact that an allele is not present in a given dataset may be of interest for the user. One the other hand, and in case there are lots of datasets, the user could be overwhelmed with unnecessary response data.

**Comment by jrambla** [comment]
@sduvaud, are you suggesting to add a query parameter to filter responses? Like &filterResponseBy=hit  ||  &filterResponseBy=miss  (I'm trying to avoid true/false because it looks misleading to me)

**Comment by sduvaud** [comment]
@jrambla: yes, that's what I meant.

**Comment by sdelatorrep** [comment]
+1

**Comment by sdelatorrep** [comment]
Hi @mcupak, any thoughts on this? You said some time ago that you wanted to give this matter some more thought. I just wanted to know if there is any news. Should we change something or close it?

**Comment by mbaudis** [comment]
So do we have an estimate about the relevance of this - resources with very many datasets? (I think Severine came up with this due to our interpolation of diagnosis==dataset => hundreds of codes). IMO, filtering responses should happen on the client side (but I may be convinced otherwise ...). This issue may void itself when considering quantitative responses (or be subsumed in their handling).

I would suggest to close this or re-phrase for quantitative responses/payload discussions.

**Comment by mcupak** [comment]
I think it's fine as it is for now, closing.
