### ISSUE TITLE
Version field in Beacon structure seems redundant/vague

### ISSUE THREAD

**Issue by kozbo** [ga4gh/beacon-team#57]
The version field in the Beacon record seems redundant because the response must include at least one BeaconDataset record, and that record type also includes a version field.  Also what version would you put in the Beacon record if you returned more than one BeaconDataset records and they each had different versions?

**Comment by mcupak** [comment]
I agree it's a bit vague, but I wouldn't say it's redundant. It's meant to be a placeholder for when a data provider decides to version their beacon and notify of its updates. For example, they could increment the version when they add a new dataset or update the API. That's why the field is optional and doesn't have any prescribed format.

This is independent from the version of the dataset, which typically reflects a change in the actual data. This field is also optional, and a data provider might choose to version only one or none of these records.

It should also be noted that the inclusion of datasets in the response is determined by a query parameter, i.e. the response might not contain any datasets.

**Comment by kozbo** [comment]
Ah, thanks @mcupak that clears things up for me :-) Closing issue.
