### ISSUE TITLE
Beacon network beacon responses do not contain URLs

### ISSUE THREAD

**Issue by david4096** [ga4gh/beacon-team#62]
Starting to look at the beacon network API and I noticed what I believe states that the network members URIs are not in the beacon-network responses. Is this by design?

https://beacon-network.org/#/developers/api/beacon-network

**Comment by mcupak** [comment]
We are exposing member URLs (as in organizations) under a [separate endpoint](https://beacon-network.org/#/developers/api/beacon-network#bn-organizations), but not the actual beacon query URLs (by design).

Also, this repository is for the API specification, a better place for discussions about the Beacon Network is here:
https://groups.google.com/forum/#!forum/ga4gh-beacon-network

**Comment by david4096** [comment]
Thanks
